- name: install npm packages
  shell: "npm install -g {{item}}"
  with_items:
    - base-x-bin@1.0.x
    - fmt2i@latest
    - http-proxy-to-socks@1.1.x
    - n@latest
    - otplib@12.x.x
    - pnpm@7.12.x
    - prettier@3.3.3
